import { NextResponse } from 'next/server';
import { gunzipSync } from 'node:zlib';
export const dynamic='force-dynamic'; export const maxDuration=60;
type Instrument={symbol:string;instrumentKey:string;sector?:string}; type Candle=[string,number,number,number,number,number,number?];
type Row={symbol:string;score:number;bias:'LONG'|'SHORT';setup:string;entry:number;stop:number;target1:number;rr:number;reasons:string[];firstReturn:number;rangePct:number;volume:number};
const num=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0; const clamp=(v:number,lo=0,hi=100)=>Math.max(lo,Math.min(hi,v));
function scoreCandle(c:Candle,prevClose:number):Row{const[,open,high,low,close,volume]=c;const range=Math.max(high-low,.0001),body=Math.abs(close-open),bodyPct=body/range,loc=(close-low)/range,ret=prevClose?((close/prevClose)-1)*100:((close/open)-1)*100,rangePct=range/Math.max(open,.0001)*100,bull=close>=open,against=bull?high-close:close-low,wick=clamp(against/range*20,0,20),structure=clamp(bodyPct*20+Math.abs(loc-.5)*40-wick),momentum=clamp(Math.abs(ret)*18),volumeScore=volume>0?10:0,total=Math.round(clamp(structure+momentum+volumeScore+8+15));const stop=bull?low-range*.08:high+range*.08,risk=range*.55,target1=bull?close+Math.max(risk*2,range):close-Math.max(risk*2,range),rr=Math.abs(target1-close)/Math.max(Math.abs(close-stop),.0001);return{symbol:'',score:total,bias:bull?'LONG':'SHORT',setup:bull?'Opening Momentum':'Opening Breakdown',entry:close,stop,target1,rr,reasons:[`${bodyPct>=.6?'Strong':'Moderate'} opening body`,`${ret>=0?'+':''}${ret.toFixed(2)}% first-candle return`,`${rangePct.toFixed(2)}% opening range`,volume>0?'Opening volume confirmed':'Volume unavailable'],firstReturn:ret,rangePct,volume}}
async function up(path:string,token:string){const r=await fetch('https://api.upstox.com'+path,{headers:{Accept:'application/json',Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error(`Upstox ${r.status}`);return r.json()}
async function getUniverse():Promise<Instrument[]>{const configured=process.env.FNO_UNIVERSE_JSON;if(configured){try{return JSON.parse(configured)}catch{throw new Error('FNO_UNIVERSE_JSON is invalid JSON')}}const r=await fetch('https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz',{cache:'no-store'});if(!r.ok)throw new Error('Unable to download Upstox NSE instrument master');const bytes=Buffer.from(await r.arrayBuffer());const records=JSON.parse(gunzipSync(bytes).toString('utf8')) as any[];const today=new Date();today.setHours(0,0,0,0);const bySymbol=new Map<string,any>();for(const x of records){if(x.segment!=='NSE_FO'||x.instrument_type!=='FUT'||x.underlying_type!=='EQUITY'||!x.underlying_symbol||!x.underlying_key)continue;const expiry=new Date(typeof x.expiry==='number'?x.expiry:x.expiry);if(expiry<today)continue;const old=bySymbol.get(x.underlying_symbol);if(!old||new Date(typeof old.expiry==='number'?old.expiry:old.expiry)>expiry)bySymbol.set(x.underlying_symbol,x)}return [...bySymbol.values()].slice(0,120).map(x=>({symbol:x.underlying_symbol,instrumentKey:x.instrument_key}))}
export async function GET(){const token=process.env.UPSTOX_ACCESS_TOKEN;if(!token)return NextResponse.json({ok:false,error:'UPSTOX_ACCESS_TOKEN is not configured'},{status:503});try{const universe=await getUniverse(),results:Row[]=[];for(let i=0;i<universe.length;i+=12){const batch=universe.slice(i,i+12);await Promise.all(batch.map(async inst=>{try{const encoded=encodeURIComponent(inst.instrumentKey);const[intra,daily]=await Promise.all([up(`/v3/historical-candle/intraday/${encoded}/minutes/5`,token),up(`/v3/market-quote/ohlc?instrument_key=${encoded}&interval=1d`,token)]);const candles:Candle[]=intra?.data?.candles||[];const first=candles.find(x=>typeof x?.[0]==='string'&&x[0].includes('09:15'))||candles[0];if(!first)return;const d=daily?.data?.[Object.keys(daily?.data||{})[0]];const row=scoreCandle(first,num(d?.prev_ohlc?.close)||num(d?.live_ohlc?.open)||first[1]);row.symbol=inst.symbol;results.push(row)}catch{}}))}results.sort((a,b)=>b.score-a.score||Math.abs(b.firstReturn)-Math.abs(a.firstReturn));return NextResponse.json({ok:true,generatedAt:new Date().toISOString(),signalTime:'09:20 IST',universe:universe.length,scanned:results.length,rows:results.slice(0,20)},{headers:{'Cache-Control':'no-store'}})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Scanner error'},{status:500})}}
