'use client';
import {useEffect,useMemo,useState} from 'react';
type Row={symbol:string;score:number;bias:'LONG'|'SHORT';setup:string;trigger:number;stop:number;target1:number;rr:number;reasons:string[];firstReturn:number;rangePct:number;volume:number;volumeRatio:number;volumeStars:number;lastPrice:number;status:string;level:string;ema20:number;emaAligned:boolean;compression:boolean;nr4:boolean;nr7:boolean;room:boolean};
type Scan={ok:boolean;error?:string;generatedAt?:string;signalTime?:string;universe?:number;scanned?:number;rows?:Row[]};
const money=(n:number)=>Number.isFinite(n)?n.toFixed(2):'—';
const statusRank=(s:string)=>s==='CONFIRMED'?4:s==='SETUP'?3:s==='WATCH'?2:s==='FAKE BREAKOUT'?1:0;
export default function Home(){
 const[data,setData]=useState<Scan|null>(null),[loading,setLoading]=useState(false),[now,setNow]=useState(new Date());
 const scan=async()=>{setLoading(true);try{const r=await fetch('/api/scan?ts='+Date.now(),{cache:'no-store'});setData(await r.json())}catch{setData({ok:false,error:'Unable to reach scanner API'})}finally{setLoading(false)}};
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{scan();const t=setInterval(scan,30000);return()=>clearInterval(t)},[]);
 const ist=useMemo(()=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now),[now]);
 const rows=data?.rows||[];const actionable=rows.filter(r=>r.status!=='NO TRADE');const leader=actionable[0];
 return <main className="shell"><header className="top"><div className="brand"><h1>PRIME TECHNICAL • INTRADAY</h1><p>F&O 09:20 Opening-Candle Intelligence • Course-based decision engine</p></div><div className="status"><span className="dot"/>LIVE • {ist} IST</div></header>
 <section className="hero"><div className="eyebrow">09:20 PRIME CANDIDATE</div><div className="leader"><div><div className="symbol">{leader?.symbol||'NO ACTIVE PRIME SETUP'}</div><p className="muted">{leader?leader.reasons.join(' • '):data?.error||'9:20 is a screening checkpoint; entry requires confirmation.'}</p></div><div className="score">{leader?leader.score:'—'} <small>/ 100</small></div></div>{leader&&<div className="heroMeta"><span className={leader.bias==='LONG'?'bull':'bear'}>{leader.bias}</span><span>{leader.setup}</span><span>Level {leader.level}</span><span>Trigger {money(leader.trigger)}</span><span>SL {money(leader.stop)}</span><span>2R {money(leader.target1)}</span><span>R:R {leader.rr.toFixed(2)}</span><span>{leader.status}</span></div>}</section>
 <section className="grid"><div className="card"><div className="label">MARKET</div><div className="value">NSE • {loading?'Updating':'Live'}</div></div><div className="card"><div className="label">F&O UNIVERSE</div><div className="value">{data?.universe??'—'}</div></div><div className="card"><div className="label">SCANNED</div><div className="value">{data?.scanned??'—'}</div></div><div className="card"><div className="label">LAST SCAN</div><div className="value">{data?.generatedAt?new Date(data.generatedAt).toLocaleTimeString('en-IN',{hour12:false}):'—'}</div></div></section>
 <div className="sectionHead"><div><h2>TOP F&O CANDIDATES</h2><p className="muted">Prime Technical: MAP → REACTION → CANDLE → VOLUME → 20 EMA → CONFIRMATION → SL → QTY</p></div><button onClick={scan} disabled={loading}>{loading?'SCANNING…':'REFRESH NOW'}</button></div>
 <section className="tablewrap"><table><thead><tr>{['Rank','Stock','Score','Bias','Setup','1st %','Level','Trigger','SL','2R Target','Volume','20 EMA','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.slice(0,10).map((r,i)=><tr key={r.symbol}><td className="rank">{i+1}</td><td><strong>{r.symbol}</strong><div className="muted">₹{money(r.lastPrice)}</div></td><td><strong>{r.score}</strong></td><td className={r.bias==='LONG'?'bull':'bear'}>{r.bias}</td><td>{r.setup}</td><td>{r.firstReturn>=0?'+':''}{r.firstReturn.toFixed(2)}%</td><td>{r.level}</td><td>{money(r.trigger)}</td><td>{money(r.stop)}</td><td>{money(r.target1)}</td><td>{r.volumeStars?'★'.repeat(r.volumeStars):'—'} {r.volumeRatio.toFixed(1)}×</td><td>{money(r.ema20)} {r.emaAligned?'✓':'—'}</td><td>{r.status}</td></tr>):<tr><td colSpan={13} className="empty">{data?.error||'Waiting for live market data…'}</td></tr>}</tbody></table></section>
 <footer className="footer">Built from the supplied Prime Technical L1–L12 course. YH/YL are previous-session references; MID and R1–R3/S1–S3 are context levels. 9:20 ranks candidates, but the course explicitly says it is not automatically an entry. Fake breakout is a separate Setup 2 state. Failed/no-trade candidates cannot become the Prime Candidate.</footer>
 </main>}
